#!/bin/bash

# create and activate virtualenv
echo -e "Creating virtualenv and installing python package dependencies..."
echo -e "=================================================================\n"
pip3 install --user virtualenv
virtualenv --python=python3 venv
source venv/bin/activate

# install dependencies using pip
pip3 install -r requirements.txt

# exit virtualenv
deactivate

# give skipper executable +x permissions
chmod +x ./skipper
echo -e "\nInstallation complete!"
echo -e "You should now be able to run Skipper with ./skipper\n"